import 'package:flutter/material.dart';

class Data {
  // static Random random = Random();

  static List<Map<String, dynamic>> profiles = [
    {
      "image": 'assets/images/7.jpg',
      "age": "21",
      "name": "Trang",
      "description": "Thích bánh kem",
      "status": "Đang tìm mối quan hệ hẹn hò",
      "address": "Đang ở Huế",
      "height": "158 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/7.jpg',
        'assets/images/11.jpg',
        'assets/images/12.jpg',
      ],
    },
    {
      "image": 'assets/images/12.jpg',
      "age": "22",
      "name": "Mỹ Uyên",
      "description": "Thích bánh kem",
      "status": "Đang tìm mối quan hệ hẹn hò",
      "address": "Đang ở Huế",
      "height": "154 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/14.jpg',
        'assets/images/15.jpg',
      ],
    },
    {
      "image": 'assets/images/13.jpg',
      "age": "22",
      "name": "Phúc",
      "description": "Thích đi chơi",
      "status": "Đang tìm mối quan hệ hẹn hò",
      "address": "Đang Đà Nẵng",
      "height": "158 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/14.jpg',
        'assets/images/15.jpg',
      ],
    },
    {
      "image": 'assets/images/14.jpg',
      "age": "20",
      "name": "Thanh Thảo",
      "description": "Thích đi chơi",
      "status": "Đang tìm người trò chuyện, tình bạn",
      "address": "Đang Đà Nẵng",
      "height": "156 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/15.jpg',
        'assets/images/16.jpg',
        'assets/images/17.jpg',
      ],
    },
    {
      "image": 'assets/images/15.jpg',
      "age": "21",
      "name": "Kim quyên",
      "description": "Đi dạo",
      "status": "Đang tìm mối quan hệ hẹn hò",
      "address": "Đang Đà Nẵng",
      "height": "156 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/17.jpg',
        'assets/images/18.jpg',
        'assets/images/19.jpg',
      ],
    },
    {
      "image": 'assets/images/16.jpg',
      "age": "20",
      "name": "Hoàng Phúc",
      "description": "Thích đi chơi",
      "status": "Đang tìm mối quan hệ hẹn hò",
      "address": "Đang Đà Nẵng",
      "height": "156 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/19.jpg',
        'assets/images/20.jpg',
        'assets/images/21.jpg',
      ],
    },
    {
      "image": 'assets/images/17.jpg',
      "age": "19",
      "name": "Mỹ Tâm",
      "description": "Thích đi chơi",
      "status": "Đang tìm mối quan hệ hẹn hò",
      "address": "Đang Đà Nẵng",
      "height": "154 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/17.jpg',
        'assets/images/15.jpg',
        'assets/images/14.jpg',
      ],
    },
    {
      "image": 'assets/images/18.jpg',
      "age": "20",
      "name": "Kim Anh",
      "description": "Thích đi chơi",
      "status": "Đang tìm mối quan hệ hẹn hò",
      "address": "Đang Đà Nẵng",
      "height": "156 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/15.jpg',
        'assets/images/16.jpg',
        'assets/images/17.jpg',
      ],
    },
    {
      "image": 'assets/images/19.jpg',
      "age": "23",
      "name": "Phụng",
      "description": "Thích đi chơi",
      "status": "Đang tìm mối quan hệ hẹn hò",
      "address": "Đang Đà Nẵng",
      "height": "156 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/19.jpg',
        'assets/images/11.jpg',
        'assets/images/15.jpg',
      ],
    },
    {
      "image": 'assets/images/20.jpg',
      "age": "22",
      "name": "Nhung",
      "description": "Thích đi chơi",
      "status": "Đang tìm mối quan hệ hẹn hò",
      "address": "Đang Đà Nẵng",
      "height": "156 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/11.jpg',
        'assets/images/14.jpg',
        'assets/images/12.jpg',
      ],
    },
    {
      "image": 'assets/images/21.jpg',
      "age": "20",
      "name": "Kim Thảo",
      "description": "Thích đi chơi",
      "status": "Đang tìm người trò chuyện, tình bạn",
      "address": "Đang Huế",
      "height": "156 cm",
      "live": "Dân Huế",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/15.jpg',
        'assets/images/16.jpg',
        'assets/images/17.jpg',
      ],
    },
    {
      "image": 'assets/images/22.jpg',
      "age": "21",
      "name": "Tú Quyên",
      "description": "Thích đi chơi",
      "status": "Đang tìm người trò chuyện, tình bạn",
      "address": "Đang Huế",
      "height": "156 cm",
      "live": "Dân Huế",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/22.jpg',
        'assets/images/17.jpg',
        'assets/images/19.jpg',
      ],
    },
    {
      "image": 'assets/images/23.jpg',
      "age": "21",
      "name": "Tuyết Nhi",
      "description": "Thích đi chơi",
      "status": "Đang tìm mối quan hệ hẹn hò",
      "address": "Đang Đà Nẵng",
      "height": "158 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/21.jpg',
        'assets/images/22.jpg',
        'assets/images/23.jpg',
      ],
    },
    {
      "image": 'assets/images/24.jpg',
      "age": "20",
      "name": "Bảo Ngọc",
      "description": "Thích đi chơi",
      "status": "Đang tìm mối quan hệ hẹn hò",
      "address": "Đang Đà Nẵng",
      "height": "146 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/24.jpg',
        'assets/images/21.jpg',
        'assets/images/20.jpg',
      ],
    },
    {
      "image": 'assets/images/25.jpg',
      "age": "20",
      "name": "Diệu Phương",
      "description": "Thích đi chơi",
      "status": "Đang tìm người trò chuyện, tình bạn",
      "address": "Đang Đà Nẵng",
      "height": "156 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/25.jpg',
        'assets/images/21.jpg',
        'assets/images/22.jpg',
      ],
    },
    {
      "image": 'assets/images/26.jpg',
      "age": "18",
      "name": "Kim Chi",
      "description": "Thích đi chơi",
      "status": "Đang tìm người trò chuyện, tình bạn",
      "address": "Đang Đà Nẵng",
      "height": "151 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/26.jpg',
        'assets/images/21.jpg',
        'assets/images/22.jpg',
      ],
    },
    {
      "image": 'assets/images/27.jpg',
      "age": "20",
      "name": "Ngọc Dung",
      "description": "Thích đi chơi",
      "status": "Đang tìm mối quan hệ hẹn hò",
      "address": "Đang Đà Nẵng",
      "height": "156 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/27.jpg',
        'assets/images/14.jpg',
        'assets/images/12.jpg',
      ],
    },
    {
      "image": 'assets/images/28.jpg',
      "age": "21",
      "name": "Mỹ Tuyên",
      "description": "Thích đi chơi",
      "status": "Đang tìm mối quan hệ hẹn hò",
      "address": "Đang Đà Nẵng",
      "height": "152 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/28.jpg',
        'assets/images/21.jpg',
        'assets/images/20.jpg',
      ],
    },
    {
      "image": 'assets/images/29.jpg',
      "age": "22",
      "name": "Yến",
      "description": "Thích đi chơi",
      "status": "Đang tìm người trò chuyện, tình bạn",
      "address": "Đang Đà Nẵng",
      "height": "153 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/29.jpg',
        'assets/images/19.jpg',
        'assets/images/15.jpg',
      ],
    },
    {
      "image": 'assets/images/30.jpg',
      "age": "23",
      "name": "Sương",
      "description": "Thích đi chơi",
      "status": "Đang tìm mối quan hệ hẹn hò",
      "address": "Đang Đà Nẵng",
      "height": "156 cm",
      "live": "Dân Đà Nẵng",
      "smoke": "Không bao giờ",
      'images': [
        'assets/images/30.jpg',
        'assets/images/24.jpg',
        'assets/images/25.jpg',
      ],
    },
  ];
}
